<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>YANA Project</title>

    <!-- Custom fonts for this theme -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body id="page-top">
    <div class="container-fluiud" style="background-color:#000;margin-bottom:30px;">
        <div class="row">
            <div class="col-12">
                <h1 style="color:#fff;text-align:center;">GRACIAS POR REGISTRARTE!</h1>
            </div>
        </div>
    </div>
    <center>
        <table style="text-align:center">
            <tr>
                <td style="text-align:center">
                    <img src="https://www.pinclipart.com/picdir/big/486-4865004_how-chat-texting-and-messaging-can-keep-us.png" style="max-width:300px">
                </td>
            </tr>
            <tr>
                <td>
                    <h1>Gracias por registrarte, %nombre%</h1>
                    <h2>Este es tu PIN de validación: %data%</h2>
                    <p>Ahora vamos a validar tu cuenta. Para ello, pulsa sobre el siguiente enlace:</p>
                    <p style="padding:40px;">
                        <a href="http://localhost/yana/activacion.php?email=%email%&pin=%data%" class="btn btn-lg btn-primary">Activar mi cuenta YANA</a>
                    </p>
                </td>
            </tr>


        </table>
    </center>
</body>

</html>
